/**
 * @fileoverview gRPC-Web generated client stub for grpc_template.v0
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.3
// source: grpc_template/v0/hello.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as grpc_template_v0_hello_pb from '../../grpc_template/v0/hello_pb';


export class HelloServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/grpc_template.v0.HelloService/SayHello',
    grpcWeb.MethodType.UNARY,
    grpc_template_v0_hello_pb.HelloRequest,
    grpc_template_v0_hello_pb.HelloResponse,
    (request: grpc_template_v0_hello_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    grpc_template_v0_hello_pb.HelloResponse.deserializeBinary
  );

  sayHello(
    request: grpc_template_v0_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null): Promise<grpc_template_v0_hello_pb.HelloResponse>;

  sayHello(
    request: grpc_template_v0_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpc_template_v0_hello_pb.HelloResponse) => void): grpcWeb.ClientReadableStream<grpc_template_v0_hello_pb.HelloResponse>;

  sayHello(
    request: grpc_template_v0_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpc_template_v0_hello_pb.HelloResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpc_template.v0.HelloService/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpc_template.v0.HelloService/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

}

